name: untitled
description: A new Flutter project.

publish_to: 'none'

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  just_audio: ^0.9.30
  firebase_auth: ^4.17.9
  firebase_core: ^2.27.0
  google_sign_in: ^6.2.1
  smooth_page_indicator: ^1.1.0
  flutter_native_splash: ^2.4.0
  animated_splash_screen: ^1.3.0
  lottie: ^3.1.0
  cloud_firestore: ^4.17.0
  page_transition: any
  firebase_storage: ^11.7.5
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.3
  percent_indicator: ^4.2.3
  intl: ^0.19.0
  firebase_messaging: ^14.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  assets:
    - android/assets/images/
    - android/assets/images/sleep/
    - android/assets/images/start_screen/
    - android/assets/logo/
    - android/assets/videos/
    - android/assets/sounds/

