// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiC6Ltp7YZBGTmLoZBrEf3JJW02uM8OuI',
    appId: '1:348447815764:android:39d1b86e63e2b7e4fe95c1',
    messagingSenderId: '348447815764',
    projectId: 'calmyo-dd42a',
    databaseURL: 'https://calmyo-dd42a-default-rtdb.firebaseio.com',
    storageBucket: 'calmyo-dd42a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbtwcF6etCqPB4XxT7u3hlAOOOA8mhjRs',
    appId: '1:348447815764:ios:d21462789eeb9d7ffe95c1',
    messagingSenderId: '348447815764',
    projectId: 'calmyo-dd42a',
    databaseURL: 'https://calmyo-dd42a-default-rtdb.firebaseio.com',
    storageBucket: 'calmyo-dd42a.appspot.com',
    iosClientId:
        '348447815764-sh25t4r71bmgm7lor7rm3tpatc268sqf.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );
}
